### ISSUE TITLE
Attempting to link Venice

### ISSUE THREAD

**Issue by loganwright** [stepanhruda/PostgreSQL-Swift#18]
For whatever reason, the library is using a venice dependency which is causing problems.  I forked and updated tag to latest commit on master which fixed it.

I can't really PR a tag, but if you updated, would be great.  The dependency appears to not be necessary and is not declared in the package.swift

**Comment by stepanhruda** [comment]
Sorry, this was probably pushed too early in error, with preparation for connection pooling, which uses Venice: https://github.com/stepanhruda/PostgreSQL-Swift/pull/15

I'm hoping we'll be getting that merged soon (unfortunately Venice was crashing Xcode and I'd really like a functional IDE integration).

**Comment by stepanhruda** [comment]
Ah, sorry again, I just figured out what's going on and fixed it. Because swiftpm can currently only point to tags and not branches, the highest tag is on a branch that's not merged yet, because I'm developing this in parallel with a project that's using it.

The dependency was of course properly specified on the branch (otherwise your swiftpm wouldn't know about it), but it probably collided with a different dependency, assuming you are using Epoch in your project.

`swift build --clean=dist && swift build` and you should now get version 0.0.6 and link fine.
